apiVersion: v1
kind: Service
metadata:
  name: itireland-config
  namespace: itireland
spec:
  selector:
    app: itireland-config
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
